### ISSUE TITLE
Transactions in wallet table are not accurate and sometimes doubled

### ISSUE THREAD

**Issue by jasonlynx** [FeeSimple/data-manager#57]
Seeing duplicate transactions in the wallet transaction table. Also after staking, not seeing any stakecpu actions.

**Comment by trungtt1981** [comment]
@jasonlynx 
The problem of duplicate entries in transaction history table has been resolved.
After doing "send", "stake" and "ram", it'll take about max 1 minute for the new tx entry to show up on the table.

Another notice is that for "unstake" action, there will be no entry showing up in the table although the user resource values are updated correctly. This is because the "unstake" process only transfers internally the XFS from the staked balance into the `unstaked` balance. After that, it'll take several days for the amount in `unstaked` balance to be transferred into the `spendable` balance.

I just wonder if we should also display the `unstaked` balance to user or not? If yes, pls let me know.
