### ISSUE TITLE
Staking/unstaking actions do not show in the wallet transaction table

### ISSUE THREAD

**Issue by jasonlynx** [FeeSimple/data-manager#66]

**Comment by trungtt1981** [comment]
**1. Why "stake" action doesn't show up in transaction history table**
It is not bug/error.
It is due to the "unstaked balance" that is a kind of hidden balance. In particular, when you perform a "stake" of some XFS amount that is lower than your hidden "unstaked balance", then there will be no real transfer/movement. Instead, the "stake" action simply transfers internally the XFS amount from the hidden "unstaked balance" to the "staked balance". So, for your current account, if you wanna see the "stake" actions again, pls try to do the stake with very high amount until you have nothing in the "unstaked balance".

From this, we have to get the "hidden" unstaked balance out to the light!

**2. Why "unstake" action doesn't show up in transaction history table**

It is because the "unstake" action simply transfers the XFS amount internally from the "staked balance" to the "unstaked balance". According to EOS, it'll take several days (e.g. 3 days) for the "unstaked balance" to be transferred into the "spendable balance"
